apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-test
  template:
    metadata:
      labels:
        app: react-test
    spec:
      containers:
        - name: react-test
          image: gcr.io/yapp16-findzone/react-test:latest
          ports:
            - containerPort: 80
---
    apiVersion: v1
    kind: Service
    metadata:
      name: react-Service
    spec:
      ports:
        - name: "8000"
          port: 8080
          targetPort: 80
      selector:
        app: react-test
      type: LoadBalancer