apiVersion: v1
kind: Service
metadata:
  name: gke-test
  labels:
    app: gke-test
spec:
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80