apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: react-nginx-deployment
  template:
    metadata:
      labels:
        app: react-nginx-deployment
    spec:
      containers:
        - name: react-nginx-deployment
          image: gcr.io/yapp16-findzone/react-test:latest
          ports:
            - containerPort: 80