apiVersion: v1
kind: Service
metadata:
  name: react-test
  labels:
    app: react-test
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: react-nginx-deployment
  type: LoadBalancer