name: release branch create

on:
  create

jobs:
  Run-Jest:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: test echo
        run: echo "생성됨!"
